export const DISPATCH_EVENTS = {
  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_IMPORTANT_DATES: 'FETCH_IMPORTANT_DATES',
  FETCH_LONG_TERM_AFFAIRS: 'FETCH_LONG_TERM_AFFAIRS',
  FETCH_CALENDAR_DAY: 'FETCH_CALENDAR_DAY',
};
