export const IPC_SIGNALS = {
  LOAD_DATA_BASE: 'LOAD_DATA_BASE',
  SAVE_DATA_BASE: 'SAVE_DATA_BASE',
  DELETE_DATA: 'DELETE_DATA',
  MOVE_TO: 'MOVE_TO',
  ADD_TAB: 'ADD_TAB',
  DELETE_TABS: 'DELETE_TABS',
  CHANGE_TABS_ORDER: 'CHANGE_TABS_ORDER',
  CHANGE_TAB: 'CHANGE_TAB',
} as const;
