export const IPC_SIGNALS = {
  LOAD_DATA_BASE: 'LOAD_DATA_BASE',
  SAVE_DATA_BASE: 'SAVE_DATA_BASE',
  DELETE_DATA: 'DELETE_DATA',
  MOVE_TO: 'MOVE_TO',
  ADD_TAB: 'ADD_TAB',
  DELETE_TABS: 'DELETE_TABS',
  CHANGE_TABS_ORDER: 'CHANGE_TABS_ORDER',
  CHANGE_TODO: 'CHANGE_TAB',
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  ADD_PROJECT: 'ADD_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',

  GET_WIDGET_SETTINGS: 'GET_WIDGET_SETTINGS',
  SET_WIDGET_AUTO_START: 'SET_WIDGET_AUTO_START',
  SET_TODO_DEADLINE: 'SET_TODO_DEADLINE',
  SAVE_TODO_IMAGE: 'SAVE_TODO_IMAGE',
  LOAD_TODO_IMAGE: 'LOAD_TODO_IMAGE',
  FIND_TODO_BY_PATTERN: 'FIND_TODO_BY_PATTERN',
  ADD_LINK_TO_TODO: 'ADD_LINK_TO_TODO',
  GET_TODO_BY_ID: 'GET_TODO_BY_ID',
  DELETE_LINK_FROM_TODO: 'DELETE_LINK_FROM_TODO',
} as const;

export const IMPORTANT_DATES_SIGNALS = {
  ADD_IMPORTANT_DATE: 'ADD_IMPORTANT_DATE',
  DELETE_IMPORTANT_DATE: 'DELETE_IMPORTANT_DATE',
  CHANGE_IMPORTANT_DATE: 'CHANGE_IMPORTANT_DATE',
  GET_ALL_IMPORTANT_DATES: 'GET_ALL_IMPORTANT_DATES',
  UPDATE_IMPORTANT_DATE_TODOS_WIDGET: 'UPDATE_IMPORTANT_DATE_TODOS_WIDGET',
};

export const LONG_TERM_AFFAIRS_SIGNALS = {
  ADD_LONG_TERM_AFFAIR: 'ADD_LONG_TERM_AFFAIR',
  DELETE_LONG_TERM_AFFAIR: 'DELETE_LONG_TERM_AFFAIR',
  CHANGE_LONG_TERM_AFFAIR: 'CHANGE_LONG_TERM_AFFAIR',
  GET_ALL_LONG_TERM_AFFAIRS: 'GET_ALL_LONG_TERM_AFFAIRS',
  MOVE_LONG_TERM_AFFAIR: 'MOVE_LONG_TERM_AFFAIR',
  UPDATE_LONG_TERM_AFFAIRS_TODOS_WIDGET:
    'UPDATE_LONG_TERM_AFFAIRS_TODOS_WIDGET',
};

export const SCHEDULE_SIGNALS = {
  ADD_SCHEDULE_DATE: 'ADD_SCHEDULE_DATE',
  DELETE_SCHEDULE_DATE: 'DELETE_SCHEDULE_DATE',
  CHANGE_SCHEDULE_DATE: 'CHANGE_SCHEDULE_DATE',
  GET_SCHEDULE_DATES: 'GET_SCHEDULE_DATES',
};
